---
title: "Assignment: 2021 VAST Mini Challenge 2"
description: |
  The Kronos Incident
author:
  - name: Connie Xia
    url: https://example.com/conniexia
date: 07-25-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.retina = 3,
                      echo = TRUE, 
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

## Introduction

This Visual Analytics Assignment is based on the VAST Challenge 2021 Mini Challenge 2. The overview of the Challenge is about a Tethys-based GAStech that has been operating a natural gas production site in the island country og Kronos. Despite bringing in remarkable profits and developing strong relationships with the Kronos government, GAStech has not been as successful in demonstrating environmental stewardship.

In January 2014, while the leaders of GAStech were celebrating their successful initial public offering (IPO), several of the company's employees go missing. It is suspected that an organisation called the Protectors of Kronos (POK) was involved in the employees' disappearance, but things may not be what they seem. 

